bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('social-auth/',
         include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/',
         views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)
    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes']),
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id,
                                              self.slug])


"""
Это модель, которая будет использоваться для хранения изображений на
платформе. Давайте посмотрим на поля данной модели:
• user: здесь указывается объект User, который сделал закладку на это
изображение. Это поле является внешним ключом, поскольку оно опре-
деляет взаимосвязь один-ко-многим: пользователь может отправлять
несколько изображений, но каждое изображение отправляется одним
пользователем. Мы использовали CASCADE для параметра on_delete, что-
бы связанные изображения удалялись при удалении пользователя;
• title: заголовок изображения;
• slug: короткое обозначение, содержащее только буквы, цифры, под-
черкивания или дефисы, которое будет использоваться для создания
красивых дружественных для поисковой оптимизации URL-адресов;
• url: изначальный URL-адрес этого изображения. Мы используем max_
length, чтобы определить максимальную длину, равную 2000 символов;
• image: файл изображения;
• description: опциональное описание изображения;
• created: дата и время, когда объект был создан в базе данных. Мы до-
бавили auto_now_add, чтобы устанавливать текущее время/дату автома-
тически при создании объекта.
В Meta-классе модели мы определили индекс базы данных в убывающем по-
рядке по полю created. Мы также добавили атрибут ordering, сообщая Django,
что по умолчанию он должен сортировать результаты по созданному полю.
Мы указываем убывающий порядок, используя дефис перед именем поля,
например -created, с тем чтобы новые изображения отображались первыми.Мы переопределим метод save() модели Image, чтобы автоматически гене-
рировать поля slug на основе значения поля title."""

bookmarks/images/forms.py
from django import forms
from .models import Image
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput,
        }

        def save(self, force_insert=False,
                 force_update=False,
                 commit=True):
            image = super().save(commit=False)
            image_url = self.cleaned_data['url']
            name = slugify(image.title)
            extension = image_url.rsplit('.', 1)[1].lower()
            image_name = f'{name}.{extension}'
            # скачать изображение с данного URL-адреса
            response = requests.get(image_url)
            image.image.save(image_name,
                             ContentFile(response.content),
                             save=False)
            if commit:
                image.save()
            return image


"""
Мы определили форму ModelForm из модели Image, включая только поля title,
url и description. Пользователи не будут вводить URL-адрес изображения
прямо в форму. Вместо этого мы предоставим им инструмент JavaScript, ко-
торый позволит им выбирать изображение с внешнего сайта, а форма будет
получать URL-адрес изображения в качестве параметра. Новый экземпляр изображения создается путем вызова метода save()
формы с commit=False.
2. URL-адрес изображения извлекается из словаря clean_data формы.
3. Имя изображения генерируется путем комбинирования названия изо-
бражения с изначальным расширением файла изображения.
4. Библиотека Python requests используется для скачивания изображе-
ния путем отправки HTTP-запроса методом GET с использованием URL-
адреса изображения. Ответ сохраняется в объекте response.
5. Вызывается метод save() поля image, передавая ему объект ContentFile,
экземпляр которого заполнен содержимым скачанного файла. Таким
путем файл сохраняется в каталог media проекта. Параметр save=False
передается для того, чтобы избежать сохранения объекта в базе данных.
6. Для того чтобы оставить то же поведение, что и в изначальном мето-
де save() модельной формы, форма сохраняется в базе данных только
в том случае, если параметр commit равен True."""


def clean_url(self):
    url = self.cleaned_data['url']
    valid_extensions = ['jpg', 'jpeg', 'png']
    extension = url.rsplit('.', 1)[1].lower()
    if extension not in valid_extensions:
        raise forms.ValidationError('The given URL does not ' \
                                    'match valid image extensions.')
    return url


"""
Здесь мы определили метод clean_url(), чтобы очищать поле url. Исходный
код работает следующим образом:
1) значение поля url извлекается путем обращения к словарю clean_data
экземпляра формы;
2) URL-адрес разбивается на части, чтобы проверить наличие валидного
расширения у файла. Если расширение невалидно, то выдается ошибка
ValidationError, и экземпляр формы не валидируется."""

bookmarks/images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
import redis
from django.conf import settings

# соединить с redis
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)


@login_required
def image_create(request):
    if request.method == 'POST':
        # форма отправлена
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():  # данные в форме валидны
            cd = form.cleaned_data
            new_image = form.save(commit=False)
        # назначить текущего пользователя элементу
        new_image.user = request.user
        new_image.save()
        create_action(request.user, 'bookmarked image', new_image)
        messages.success(request,
                         'Image added successfully')
        # перенаправить к представлению детальной
        # информации о только что созданном элементе
        return redirect(new_image.get_absolute_url())

    else:
        # скомпоновать форму с данными,
        # предоставленными букмарклетом методом GET
        form = ImageCreateForm(data=request.GET)
    return render(request,
                  'images/image/create.html',
                  {'section': 'images',
                   'form': form})


"""
Здесь мы создали представление хранения изображений на сайте. В пред-
ставление image_create был добавлен декоратор login_required, чтобы предот-
вращать доступ неаутентифицированных пользователей. Вот как это пред-
ставление работает.
1. Для создания экземпляра формы необходимо предоставить начальные
данные через HTTP-запрос методом GET. Эти данные будут состоять
из атрибутов url и title изображения с внешнего веб-сайта. Оба па-
раметра будут заданы в запросе GET букмарклетом JavaScript, который
мы создадим позже. Пока же можно допустить, что эти данные будут
иметься в запросе.
2. После того как форма передана на обработку с по мощью HTTP-запроса
методом POST, она валидируется методом form.is_valid(). Если данные
в форме валидны, то создается новый экземпляр Image путем сохране-
ния формы методом form.save(commit=False). Новый экземпляр в базе
данных не сохраняется, если commit=False.
3. В новый экземпляр изображения добавляется связь с текущим пользо-
вателем, который выполняет запрос: new_image.user = request.user. Так
мы будем знать, кто закачивал каждое изображение.
4. Объект Image сохраняется в базе данных.
5. Наконец, с по мощью встроенного в Django фреймворка сообщений
создается сообщение об успехе, и пользователь перенаправляется на
канонический URL-адрес нового изображения."""


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # увеличить общее число просмотров изображения на 1
    total_views = r.incr(f'image:{image.id}:views')
    r.zincrby('image_ranking', 1,
              image.id)  # Команда zincrby() используется для сохранения просмотров изображений в сортированном множестве с ключом image:ranking.
    return render(request, 'images/image/detail.html',
                  {'section': 'images',
                   'image': image,
                   'total_views': total_views})


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом,
        # то доставить первую страницу
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            # Если AJAX-запрос и страница вне диапазона,
            # то вернуть пустую страницу
            return HttpResponse('')
        # Если страница вне диапазона,
        # то вернуть последнюю страницу результатов
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(request,
                      'images/image/list_images.html',
                      {'section': 'images',
                       'images': images})
    return render(request,
                  'images/image/list.html',
                  {'section': 'images',
                   'images': images})


"""
В этом представлении создается набор запросов QuerySet, чтобы извлекать
все изображения из базы данных. Затем формируется объект Paginator, чтобы
разбивать результаты на страницы, беря по восемь изображений на стра-
ницу. Извлекается HTTP GET-параметр page, чтобы получить запрошенный
номер страницы. Извлекается HTTP GET-параметр images_only, чтобы узнать,
должна ли прорисовываться вся страница целиком или же только новые
изображения. Мы будем прорисовывать всю страницу целиком, когда она
запрашивается браузером. Однако мы будем прорисовывать HTML только
с новыми изображениями в случае запросов Fetch API, поскольку мы будем
добавлять их в существующую HTML-страницу.
Исключение EmptyPage будет вызываться в случае, если запрошенная стра-
ница находится вне допустимого диапазона. Если это так и нужно прори-
совывать только изображения, то будет возвращаться пустой HttpResponse.
Такой подход позволит останавливать AJAX-ориентированное постраничное
разбиение на стороне клиента при достижении последней страницы. Резуль-
таты прорисовываются с использованием двух разных шаблонов:
• в случае HTTP-запросов на JavaScript, которые будут содержать пара-
метр images_only, будет прорисовываться шаблон list_images.html. Этот
шаблон будет содержать изображения только запрошенной страницы;
• в случае браузерных запросов будет прорисовываться шаблон list.html.
Этот шаблон будет расширять шаблон base.html, чтобы отображать всю
страницу целиком, и будет вставлять шаблон list_images.html, который
будет вставлять список изображений."""


@login_required
def image_ranking(request):
    # получить словарь рейтинга изображений
    image_ranking = r.zrange('image_ranking', 0, -1,
                             desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # получить наиболее просматриваемые изображения
    most_viewed = list(Image.objects.filter(
        id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images',
                   'most_viewed': most_viewed})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
</form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
<h1>{{ image.title }}</h1>
{% load thumbnail %}
<a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">

    <!--    Мы определили миниатюру с фиксированной шириной 300 пикселов и гиб- -->
    <!--кой высотой, чтобы поддерживать соотношение сторон, используя значение-->
    <!--0. Когда пользователь загружает эту страницу в первый раз, будет сформиро- -->
    <!--вано изображение-миниатюра. Миниатюра хранится в том же каталоге, что-->
    <!--и исходный файл.-->

</a>
{% with total_likes=image.users_like.count %}
<div class="image-info">
    <div>
<span class="count">
<span class="total">{{ total_likes }}</span>
like{{ total_likes|pluralize }}
</span>
        <span class="count">
{{ total_views }} view{{ total_views|pluralize }}
</span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_
like %}un{% endif %}like" class="like button">
            {% if request.user not in users_like %}
            Like
            {% else %}
            Unlike
            {% endif %}

            <!--В приведенном выше исходном коде в шаблонный тег {% with %} была-->
            <!--добавлена еще одна переменная, чтобы хранить результаты запроса image.-->
            <!--users_like.all и избегать многократного исполнения запроса к базе дан- -->
            <!--ных. Указанная переменная используется для проверки наличия текущего-->
            <!--пользователя в списке с по мощью {% if request.user in users_like %}, а за- -->
            <!--тем с по мощью {% if request.user not in users_like %}. Эта же переменная-->
            <!--используется для прокручивания пользователей, которые поставили этому-->
            <!--изображению лайк, в цикле с по мощью {% for user in users_like %}.-->

        </a>
    </div>
    {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in image.users_like.all %}
    <div>
        {% if user.profile.photo %}
        <img src="{{ user.profile.photo.url }}">
        {% endif %}
        <p>{{ user.first_name }}</p>
    </div>
    {% empty %}
    Nobody likes this image yet.
    {% endfor %}
</div>
{% endwith %}
{% endblock %}

{% block domready %}
const url = '{% url "images:like" %}';
var options = {
method: 'POST',
headers: {'X-CSRFToken': csrftoken},
mode: 'same-origin'
}
document.querySelector('a.like')
.addEventListener('click', function(e){
e.preventDefault();
var likeButton = this;

// добавить тело запроса
var formData = new FormData();
formData.append('id', likeButton.dataset.id);
formData.append('action', likeButton.dataset.action);
options['body'] = formData;
// отправить HTTP-запрос
fetch(url, options)
.then(response => response.json())
.then(data => {
if (data['status'] === 'ok')
{
var previousAction = likeButton.dataset.action;
// переключить текст кнопки и атрибут data-action
var action = previousAction === 'like' ? 'unlike' : 'like';
likeButton.dataset.action = action;
likeButton.innerHTML = action;
// обновить количество лайков
var likeCount = document.querySelector('span.count .total');
var totalLikes = parseInt(likeCount.innerHTML);
likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes – 1;
}
})

});
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
    {% include "images/image/list_images.html" %}
</div>
{% endblock %}

{% block domready %}
var page = 1;
var emptyPage = false;
var blockRequest = false;
window.addEventListener('scroll', function(e) {
var margin = document.body.clientHeight – window.innerHeight – 200;
if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
blockRequest = true;
page += 1;
fetch('?images_only=1&page=' + page)
.then(response => response.text())
.then(html => {
if (html === '') {
emptyPage = true;
}
else {
var imageList = document.getElementById('image-list');
imageList.insertAdjacentHTML('beforeEnd', html);
blockRequest = false;
}
})
}
});
// Запустить события прокрутки
const scrollEvent = new Event('scroll');
window.dispatchEvent(scrollEvent);
{% endblock %}

bookmarks/images/templates/images/image/list_images.html
<!--Приведенный выше шаблон отображает список изображений. Он будет ис- -->
<!--пользоваться для того, чтобы возвращать результаты AJAX-запросов. В пока- -->
<!--занном выше исходном коде изображения в списке прокручиваются в цикле,-->
<!--и по каждому изображению генерируется квадратная миниатюра. Размер-->
<!--миниатюр нормализуется до 300×300 пикселов. Также используется опция-->
<!--умной обрезки smart. Данная опция указывает на то, что изображение должно-->
<!--постепенно обрезаться до требуемого размера путем удаления срезов с краев-->
<!--с наименьшей энтропией.-->

{% load thumbnail %}
{% for image in images %}
<div class="image">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
        </a>
    </a>
    <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">
            {{ image.title }}
        </a>
    </div>
</div>
{% endfor %}

bookmarks/images/templates/images/image/rating.html
{% extends "base.html" %}
{% block title %}Images ranking{% endblock %}
{% block content %}
<h1>Images ranking</h1>
<ol>
    {% for image in most_viewed %}
    <li>
        <a href="{{ image.get_absolute_url }}">
            {{ image.title }}
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}